# pipeline依赖的docker镜像
image: docker-reg.basebit.me:5000/base/centos7_pyenv
variables:
  IMAGE_NAME: pmxrisk_backend
  PRODUCTION_VERSION: 1.0.0
  WECHAT_IMAGE_NAME: pmxwechat
  WECHAT_PRODUCTION_VERSION: 1.0.0
  OP_IMAGE_NAME: pmxrisk-op
  OP_PRODUCTION_VERSION: 1.0.0
# 所有stage之前的操作
before_script:
 - whoami
 - echo "I am in before_script"
# 所有stage之后的操作
after_script:
 - echo "I am in after_script"
# 本次pipeline的stages
stages:
 - production
# 部署生成环境镜像
deploy_service:
   image: docker-reg.basebit.me:5000/base/docker:latest
   stage: production
   only:
    - dev
   script:
    - cd asthma
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ./id_rsa
    - docker build -f Dockerfile -t docker-reg.basebit.me:5000/service/"${IMAGE_NAME}":"${PRODUCTION_VERSION}" .
    - docker push docker-reg.basebit.me:5000/service/"${IMAGE_NAME}":"${PRODUCTION_VERSION}"
   # 定义job运行时机
   when: manual

deploy_wechat:
   image: docker-reg.basebit.me:5000/base/docker:latest
   stage: production
   only:
    - dev
   script:
    - cd wechat
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ./id_rsa
    - docker build -f Dockerfile -t docker-reg.basebit.me:5000/service/"${WECHAT_IMAGE_NAME}":"${WECHAT_PRODUCTION_VERSION}" .
    - docker push docker-reg.basebit.me:5000/service/"${WECHAT_IMAGE_NAME}":"${WECHAT_PRODUCTION_VERSION}"
   # 定义job运行时机
   when: manual
   
deploy_op_fe:
   image: docker-reg.basebit.me:5000/base/docker:latest
   stage: production
   only:
    - dev
   script:
    - cd op_fe
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ./id_rsa
    - docker build -f Dockerfile -t docker-reg.basebit.me:5000/service/"${OP_IMAGE_NAME}":"${OP_PRODUCTION_VERSION}" .
    - docker push docker-reg.basebit.me:5000/service/"${OP_IMAGE_NAME}":"${OP_PRODUCTION_VERSION}"
   # 定义job运行时机
   when: manual   
   
